### ISSUE TITLE
[Exception] `System.AggregateException`: CodeBase is not supported on assemblies loaded from a single-file bundle.

### ISSUE THREAD

**Issue by hack003** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#103]
MRF v0.10 report this error at start :

```
Unhandled exception. System.AggregateException: One or more errors occurred. (CodeBase is not supported on assemblies loaded from a single-file bundle.)
 ---> System.NotSupportedException: CodeBase is not supported on assemblies loaded from a single-file bundle.
   at System.Reflection.RuntimeAssembly.get_CodeBase()
   at PuppeteerSharp.BrowserFetcher.GetExecutablePath() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\BrowserFetcher.cs:line 356
   at PuppeteerSharp.BrowserFetcher..ctor() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\BrowserFetcher.cs:line 53
   at PuppeteerPlus.Utility.TryGetBuildInBrowser(String& browserPath) in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Puppeteer Plus/Utility.cs:line 129
   at MicrosoftRewardsFarmer.Utilities.PuppeteerPlusUtility.GetBrowserAsync() in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer/Utilities/PuppeteerPlusUtility.cs:line 34
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean )
   at System.Threading.Tasks.Task`1.get_Result()
   at MicrosoftRewardsFarmer.TUI.Program.StartFarming() in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer.TUI/Program.cs:line 74
   at MicrosoftRewardsFarmer.TUI.Program.Main(String[] args) in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer.TUI/Program.cs:line 53
```

0.9.3 runs normally, 0.10 appears this error, .net, vc+ are installed, I really can't understand where there is a problem, ask for help

**Comment by leftshine** [comment]
same error with me

**Comment by glycerinevaseline** [comment]
same error with me

**Comment by ArnavVarshney** [comment]
same here

**Comment by yushunqwq** [comment]
same here

**Comment by Tom60chat** [comment]
It happens on some computer, as if it had an dependency issue.

It's not related to dotnet SDK, so...

**Comment by Tom60chat** [comment]
So PublishSingleFile don't work anymore, because I have splited the projet in small librabries.

I will need to diseable PublishSingleFile, and use https://github.com/nulastudio/NetBeauty2

For now, you can recompile the projet with the dotnet SDK 6 and `dotnet build`
