### ISSUE TITLE
[Exception]: `PuppeteerSharp.WaitTaskTimeoutException`: waiting for selector '#microsoft' failed

### ISSUE THREAD

**Issue by Tom60chat** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#104]
Stuck on the init phase

**Screenshots**
![Screenshot](https://media.discordapp.net/attachments/1066284574499409945/1085321299724873838/image.png)

**StackTrace**
```
PuppeteerSharp.WaitTaskTimeoutException: waiting for selector '#microsoft' failed: timeout 300000 ms exceeded
   at PuppeteerSharp.DOMWorld.WaitForSelectorInPageAsync(String queryOne, String selector, WaitForSelectorOptions options, PageBinding[] bindings) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\DOMWorld.cs:line 354
   at PuppeteerSharp.CustomQueriesManager.<>c__DisplayClass13_0.<<MakeQueryHandler>b__1>d.MoveNext() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\CustomQueriesManager.cs:line 159
--- End of stack trace from previous location ---
   at PuppeteerSharp.DOMWorld.WaitForSelectorAsync(String selector, WaitForSelectorOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\DOMWorld.cs:line 498
   at PuppeteerSharp.Frame.WaitForSelectorAsync(String selector, WaitForSelectorOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Frame.cs:line 115
   at MicrosoftRewardsFarmer.Farmer.ConnectToMicrosoft(IPage page, Session session, Account account, IProgress`1 progress) in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer/Farmer.cs:line 154
   at MicrosoftRewardsFarmer.Farmer.StartAsync(IProgress`1 progress) in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer/Farmer.cs:line 92
   at MicrosoftRewardsFarmer.Farmer.StartAsync(IProgress`1 progress) in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer/Farmer.cs:line 120
   at MicrosoftRewardsFarmer.TUI.Program.<>c.<<StartFarming>b__4_0>d.MoveNext() in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer.TUI/Program.cs:line 109
```

**Comment by hack003** [comment]
Same

**Comment by Re-hd** [comment]
[2023-03-17 18.14.20.txt](https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/files/11007358/2023-03-17.18.14.20.txt)
[2023-03-18 10.53.32.txt](https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/files/11007359/2023-03-18.10.53.32.txt)

**Comment by PXfable** [comment]
可以尝试用管理员模式运行
