### ISSUE TITLE
[exception] farmer - waiting for selector 'div[class='points clearfix]' failed: timeout 30000 ms exceeeded 0.10

### ISSUE THREAD

**Issue by kuramadur30X** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#108]
I have this error.
![Imagem do WhatsApp de 2023-03-15 à(s) 12 03 49](https://user-images.githubusercontent.com/121198725/225352319-03f3c759-72c5-4f16-b6b3-ba785f7bf690.jpg)
![Imagem do WhatsApp de 2023-03-15 à(s) 12 01 34](https://user-images.githubusercontent.com/121198725/225352324-fb2ea34e-970a-4024-94ed-ed1eb05163fd.jpg)
and I also did not find the place where the log is generated.
![Imagem do WhatsApp de 2023-03-15 à(s) 12 07 57](https://user-images.githubusercontent.com/121198725/225352865-a3a166d7-a528-494e-8839-9f6740ac5256.jpg)

**Comment by rzZlm** [comment]
Same here, looks like a random error, run the farmin on 3 accounts.

> I also did not find the place where the log is generated.
Add a static path to the Settings.json, but unfortunately the log doesn't show much information.

```
Exception 0: Farmer
PuppeteerSharp.WaitTaskTimeoutException: waiting for selector 'div[class="points clearfix"]' failed: timeout 30000 ms exceeded
   at PuppeteerSharp.DOMWorld.WaitForSelectorInPageAsync(String queryOne, String selector, WaitForSelectorOptions options, PageBinding[] bindings) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\DOMWorld.cs:line 354
   at PuppeteerSharp.CustomQueriesManager.<>c__DisplayClass13_0.<<MakeQueryHandler>b__1>d.MoveNext() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\CustomQueriesManager.cs:line 159
--- End of stack trace from previous location ---
   at PuppeteerSharp.DOMWorld.WaitForSelectorAsync(String selector, WaitForSelectorOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\DOMWorld.cs:line 498
   at PuppeteerSharp.Frame.WaitForSelectorAsync(String selector, WaitForSelectorOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Frame.cs:line 115
   at MicrosoftRewardsFarmer.MsRewards.GetCardsAsync(IPage page, IProgress`1 progress) in C:\MyFolder\GitHub\Microsoft-Rewards-Farmer-Sharp\Microsoft Rewards Farmer\MsRewards.cs:line 141
   at MicrosoftRewardsFarmer.Farmer.ResolveCardsAsync(IPage page, IProgress`1 progress) in C:\MyFolder\GitHub\Microsoft-Rewards-Farmer-Sharp\Microsoft Rewards Farmer\Farmer.cs:line 195
   at MicrosoftRewardsFarmer.Farmer.StartAsync(IProgress`1 progress) in C:\MyFolder\GitHub\Microsoft-Rewards-Farmer-Sharp\Microsoft Rewards Farmer\Farmer.cs:line 107
   at MicrosoftRewardsFarmer.Farmer.StartAsync(IProgress`1 progress) in C:\MyFolder\GitHub\Microsoft-Rewards-Farmer-Sharp\Microsoft Rewards Farmer\Farmer.cs:line 120
   at MicrosoftRewardsFarmer.TUI.Program.<>c.<<StartFarming>b__4_0>d.MoveNext() in C:\MyFolder\GitHub\Microsoft-Rewards-Farmer-Sharp\Microsoft Rewards Farmer.TUI\Program.cs:line 109

Exception 
[0](0/0) - 62286 points: [Exception] Farmer - waiting for selector 'div[class="points clearfix"]' failed: timeout 30000 ms exceeded

```

**Comment by kuramadur30X** [comment]
where do i access this log?
I didn't find.

**Comment by Tom60chat** [comment]
Kind of like #90

I would like to know on what website this is happening?
And if you use a VPN?

> the log doesn't show much information

Yup, he need to be improved.

**Comment by rzZlm** [comment]
Please create one Log-file for each run (and the log Levels do not show a difference).

something like e.g. (make sure the path is a forward-slash)
```
...
  "Loggers": {
    "File": [
      {
        "URI": "C:/MyLog/GitHub/Logs",
        "Levels": [
          "Log",
          "Exception",
          "Summary"
        ]
      }
    ]
...
```

**Comment by Tom60chat** [comment]
@rzZlm I don't understand this exactly what logger do.
But yeah he seam to be bugged.

**Comment by Tom60chat** [comment]
@DarkEnergy666 
> Please create one Log-file for each run (and the log Levels do not show a difference).

Version 0.10.1 is out, I invite you to test this version.

You can get it at the following address: https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/releases/tag/v0.10.1-beta1
