### ISSUE TITLE
v0.10.1-beta1 :[Exception] Farmer - Timeout of 30000 ms exceeded

### ISSUE THREAD

**Issue by BigYty** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#117]
[Exception] Farmer - Timeout of 30000 ms exceeded

**Comment by Tom60chat** [comment]
Yeah, not very helpful.

But actually this is happening a lot everywhere.

May you share your log file when this issue happened?

**Comment by thisiswloq** [comment]
same error

log:
------------------------------------------
Exception 0: Farmer
System.TimeoutException: Timeout of 300000 ms exceeded
   at PuppeteerSharp.Helpers.TaskHelper.<>c__DisplayClass2_0.<WithTimeout>b__0() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Helpers\TaskHelper.cs:line 48
   at PuppeteerSharp.Helpers.TaskHelper.WithTimeout(Task task, Func`1 timeoutAction, TimeSpan timeout, CancellationToken cancellationToken) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Helpers\TaskHelper.cs:line 93
   at PuppeteerSharp.FrameManager.WaitForFrameNavigationAsync(Frame frame, NavigationOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\FrameManager.cs:line 106
   at MicrosoftRewardsFarmer.Bing.SignInToMicrosoftAsync(IPage page, Account account, IProgress`1 progress) in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer/Bing.cs:line 107
   at MicrosoftRewardsFarmer.Farmer.ConnectToMicrosoft(IPage page, Session session, Account account, IProgress`1 progress) in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer/Farmer.cs:line 185
   at MicrosoftRewardsFarmer.Farmer.StartAsync(IProgress`1 progress) in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer/Farmer.cs:line 92
   at MicrosoftRewardsFarmer.Farmer.StartAsync(IProgress`1 progress) in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer/Farmer.cs:line 120
   at MicrosoftRewardsFarmer.TUI.Program.<>c.<<StartFarming>b__4_0>d.MoveNext() in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer.TUI/Program.cs:line 125

Exception 
------------------------------------------

- latest version
- account working without latest version
- with version 0.9.2 working fine

**Comment by Quendi6** [comment]
> on a retry i get also a new error:
> 
> [Exception] Farmer - Object reference not set to an instance of an object.
> 
> Exception 0: Farmer System.NullReferenceException: Object reference not set to an instance of an object. at PuppeteerSharp.DOMWorld.GetDocument() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\DOMWorld.cs:line 668 at PuppeteerSharp.DOMWorld.QuerySelectorAsync(String selector) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\DOMWorld.cs:line 200 at MicrosoftRewardsFarmer.Farmer.ConnectToMicrosoft(IPage page, Session session, Account account, IProgress`1 progress) in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer/Farmer.cs:line 152 at MicrosoftRewardsFarmer.Farmer.StartAsync(IProgress`1 progress) in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer/Farmer.cs:line 92 at MicrosoftRewardsFarmer.Farmer.StartAsync(IProgress`1 progress) in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer/Farmer.cs:line 120 at MicrosoftRewardsFarmer.TUI.Program.<>c.<b__4_0>d.MoveNext() in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer.TUI/Program.cs:line 125
> 
> Exception

I have exactly same error and log details
