### ISSUE TITLE
When I run v0.10.1 on centos7 I get the following error.

### ISSUE THREAD

**Issue by BigYty** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#126]
[root@XD rewards]# ./st
Unhandled exception.
System.AggregateException: One or more errors occurred. (CodeBase is not supported on assemblies loaded from a single-file bundle.)
 ---> System.NotSupportedException: CodeBase is not supported on assemblies loaded from a single-file bundle.
   at System.Reflection.RuntimeAssembly.get_CodeBase()
   at PuppeteerSharp.BrowserFetcher.GetExecutablePath() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\BrowserFetcher.cs:line 356
   at PuppeteerSharp.BrowserFetcher..ctor() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\BrowserFetcher.cs:line 53
   at PuppeteerPlus.Utility.TryGetBuildInBrowser(String& browserPath) in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Puppeteer Plus/Utility.cs:line 129
   at MicrosoftRewardsFarmer.Utilities.PuppeteerPlusUtility.GetBrowserAsync() in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer/Utilities/PuppeteerPlusUtility.cs:line 34
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean )
   at System.Threading.Tasks.Task`1.get_Result()
   at MicrosoftRewardsFarmer.TUI.Program.StartFarming() in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer.TUI/Program.cs:line 90
   at MicrosoftRewardsFarmer.TUI.Program.Main(String[] args) in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer.TUI/Program.cs:line 60

Press any key to exit.

**Comment by Tom60chat** [comment]
dup of #111

**Comment by Tom60chat** [comment]
of wait, I read to fast

**Comment by Tom60chat** [comment]
Interesting the error is happening  on linux too.

Well, if you can try to compile the app from source, this will be fixed until next release.

**Comment by Xzonn** [comment]
Just change
``` xml
<PublishSingleFile>true</PublishSingleFile>
```
to
``` xml
<PublishSingleFile>false</PublishSingleFile>
```
in `Microsoft Rewards Farmer.TUI/Properties/PublishProfiles/linux-x64.pubxml` (and `arm/arm64`), like [this](https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/commit/4ecc8ba4e4a013dfddd64a710461aee1bed72917), and compile it. After that it works for me on Ubuntu-20.04. This may also fix #133 and #138.

**Comment by Tom60chat** [comment]
I make the merge, you can use the dev branch to compile a "working" version of MRF.
