### ISSUE TITLE
[Exception] Farmer - waiting for selector '.wk_button' failed: timeout 30000 ms exceeded. Happens randomly.

### ISSUE THREAD

**Issue by VanMeh** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#132]
Some days all accounts are fine and everything works on the first try, while on others I might need to restart the app like 5-7 times untill all acounts are finished. 

Exception 3: Farmer
PuppeteerSharp.WaitTaskTimeoutException: waiting for selector '.wk_button' failed: timeout 30000 ms exceeded
   at PuppeteerSharp.DOMWorld.WaitForSelectorInPageAsync(String queryOne, String selector, WaitForSelectorOptions options, PageBinding[] bindings) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\DOMWorld.cs:line 362
   at PuppeteerSharp.CustomQueriesManager.<>c__DisplayClass13_0.<<MakeQueryHandler>b__1>d.MoveNext() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\CustomQueriesManager.cs:line 160
--- End of stack trace from previous location ---
   at PuppeteerSharp.DOMWorld.WaitForSelectorAsync(String selector, WaitForSelectorOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\DOMWorld.cs:line 499
   at PuppeteerSharp.Frame.WaitForSelectorAsync(String selector, WaitForSelectorOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Frame.cs:line 125
   at MicrosoftRewardsFarmer.MsRewards.ProceedWKQuizAsync(IPage cardPage) in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer/MsRewards.cs:line 354
   at MicrosoftRewardsFarmer.MsRewards.ProceedCardAsync(IPage cardPage) in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer/MsRewards.cs:line 302
   at MicrosoftRewardsFarmer.MsRewards.ProceedCardsAsync(IPage page, IElementHandle[] cardsElement, IProgress`1 progress) in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer/MsRewards.cs:line 208
   at MicrosoftRewardsFarmer.Farmer.ResolveCardsAsync(IPage page, IProgress`1 progress) in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer/Farmer.cs:line 198
   at MicrosoftRewardsFarmer.Farmer.StartAsync(IProgress`1 progress) in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer/Farmer.cs:line 107
   at MicrosoftRewardsFarmer.Farmer.StartAsync(IProgress`1 progress) in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer/Farmer.cs:line 120
   at MicrosoftRewardsFarmer.TUI.Program.<>c.<<StartFarming>b__4_0>d.MoveNext() in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer.TUI/Program.cs:line 125

**Comment by VanMeh** [comment]
After running it agains got another error:

Exception 4: Farmer
PuppeteerSharp.WaitTaskTimeoutException: waiting for selector 'div[class="points clearfix"]' failed: timeout 30000 ms exceeded
   at PuppeteerSharp.DOMWorld.WaitForSelectorInPageAsync(String queryOne, String selector, WaitForSelectorOptions options, PageBinding[] bindings) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\DOMWorld.cs:line 354
   at PuppeteerSharp.CustomQueriesManager.<>c__DisplayClass13_0.<<MakeQueryHandler>b__1>d.MoveNext() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\CustomQueriesManager.cs:line 159
--- End of stack trace from previous location ---
   at PuppeteerSharp.DOMWorld.WaitForSelectorAsync(String selector, WaitForSelectorOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\DOMWorld.cs:line 498
   at PuppeteerSharp.Frame.WaitForSelectorAsync(String selector, WaitForSelectorOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Frame.cs:line 125
   at MicrosoftRewardsFarmer.MsRewards.GetCardsAsync(IPage page, IProgress`1 progress) in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer/MsRewards.cs:line 141
   at MicrosoftRewardsFarmer.Farmer.ResolveCardsAsync(IPage page, IProgress`1 progress) in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer/Farmer.cs:line 195
   at MicrosoftRewardsFarmer.Farmer.StartAsync(IProgress`1 progress) in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer/Farmer.cs:line 107
   at MicrosoftRewardsFarmer.Farmer.StartAsync(IProgress`1 progress) in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer/Farmer.cs:line 120
   at MicrosoftRewardsFarmer.TUI.Program.<>c.<<StartFarming>b__4_0>d.MoveNext() in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer.TUI/Program.cs:line 125

**Comment by throwaway45632** [comment]
Yes I'm having the same issue, after restarting the farmer like 10 times I was able to finish

**Comment by Tom60chat** [comment]
> After running it agains got another error:...

See #108

**Comment by Tom60chat** [comment]
Might go with the global timeout issue.
