### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by KendallDoesCoding** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#137]
Unhandled exception. System.IO.IOException: The process cannot access the file 'C:\Users\Dell\Downloads\win-x64\win-x64\Logs\2023-03-27 10.33.37.txt' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String , FileMode , FileAccess , FileShare , FileOptions )
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )
   at System.IO.Strategies.AsyncWindowsFileStreamStrategy..ctor(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream , String , FileMode , FileAccess , FileShare , Int32 , FileOptions , Int64 )
   at System.IO.FileStream..ctor(String , FileMode , FileAccess , FileShare , Int32 , FileOptions , Int64 )
   at System.IO.FileStream..ctor(String , FileMode , FileAccess , FileShare , Int32 , FileOptions )
   at System.IO.File.AsyncStreamWriter(String , Encoding , Boolean )
   at System.IO.File.AppendAllTextAsync(String , String , Encoding , CancellationToken )
   at System.IO.File.AppendAllTextAsync(String , String , CancellationToken )
   at MicrosoftRewardsFarmer.Log.Types.FileLogger.Write(String content) in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer.Log/Types/FileLogger.cs:line 38
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object )
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

**Comment by jackjack21-pixel** [comment]
It looks like you’re encountering an error while running the Microsoft Rewards Farmer Sharp program. The error message suggests that the file C:\Users\Dell\Downloads\win-x64\win-x64\Logs\2023-03-27 10.33.37.txt cannot be accessed because it is being used by another process. This could happen if another program is using the file or if the file is open in another window.

Have you tried closing any programs or windows that might be using the file and then running the program again?


If closing any programs or windows that might be using the file doesn’t work, you could try restarting your computer to release any locks on the file. If the issue persists, you could try running the program as an administrator or checking the permissions on the file to make sure you have the necessary access.

**Comment by KendallDoesCoding** [comment]
It worked after restarting my computer. Thanks
