### ISSUE TITLE
[Exception] Farmer - Execution context was destroyed, most likely because of a navigation.

### ISSUE THREAD

**Issue by ShubhamC1209** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#139]
Exception 0: Farmer
PuppeteerSharp.EvaluationFailedException: Execution context was destroyed, most likely because of a navigation.
 ---> PuppeteerSharp.MessageException: Execution context was destroyed, most likely because of a navigation.
   at PuppeteerSharp.CDPSession.SendAsync(String method, Object args, Boolean waitForCallback) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\CDPSession.cs:line 95
   at PuppeteerSharp.CDPSession.SendAsync[T](String method, Object args) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\CDPSession.cs:line 57
   at PuppeteerSharp.ExecutionContext.ExecuteEvaluationAsync(String method, Object args) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\ExecutionContext.cs:line 195
   --- End of inner exception stack trace ---
   at PuppeteerSharp.ExecutionContext.ExecuteEvaluationAsync(String method, Object args) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\ExecutionContext.cs:line 195
   at PuppeteerSharp.ExecutionContext.EvaluateFunctionHandleAsync(String script, Object[] args) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\ExecutionContext.cs:line 57
   at PuppeteerSharp.DOMWorld.<GetDocumentAsync>g__EvalauteDocumentInContext|58_0() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\DOMWorld.cs:line 555
   at PuppeteerSharp.DOMWorld.WaitForSelectorAsync(String selector, WaitForSelectorOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\DOMWorld.cs:line 497
   at PuppeteerSharp.Frame.WaitForSelectorAsync(String selector, WaitForSelectorOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Frame.cs:line 115
   at MicrosoftRewardsFarmer.Bing.SignInToMicrosoftAsync(IPage page, Account account, IProgress`1 progress) in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer/Bing.cs:line 112
   at MicrosoftRewardsFarmer.Farmer.ConnectToMicrosoft(IPage page, Session session, Account account, IProgress`1 progress) in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer/Farmer.cs:line 185
   at MicrosoftRewardsFarmer.Farmer.StartAsync(IProgress`1 progress) in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer/Farmer.cs:line 92
   at MicrosoftRewardsFarmer.Farmer.StartAsync(IProgress`1 progress) in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer/Farmer.cs:line 120
   at MicrosoftRewardsFarmer.TUI.Program.<>c.<<StartFarming>b__4_0>d.MoveNext() in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer.TUI/Program.cs:line 125

**Comment by rndcosmo** [comment]
How many accounts are you using at the same time? I am getting this mistake when using more than 3.  Trying to work around it with the cmd arguments "-n, --farms-limit 3" at the moment ...

**Comment by ShubhamC1209** [comment]
I am using 3 accounts at the same time too.

**Comment by Tom60chat** [comment]
Check #95
