### ISSUE TITLE
Unhandled exception. System.AggregateException: One or more errors occurred.

### ISSUE THREAD

**Issue by Skeppr** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#150]
**Describe the bug**
Browser crashes when trying to run MRF

**To Reproduce**

Download 0.9.2-arm(32) with wget
Unzip
Edit settings and permissions with chmod and all that stuff
./'Microsoft Rewards Farmer'
crashes 

```
pi@bigdata:~/0.9.2 $ ./'Microsoft Rewards Farmer' -n 2 -b built-in
Unhandled exception. System.AggregateException: One or more errors occurred. (An error occurred trying to start process '/home/pi/0.9.2/.local-chromium/Linux-970485/chrome-linux/chrome' with working directory '/home/pi/0.9.2'. Exec format error) (An error occurred trying to start process '/home/pi/0.9.2/.local-chromium/Linux-970485/chrome-linux/chrome' with working directory '/home/pi/0.9.2'. Exec format error)
 ---> System.ComponentModel.Win32Exception (8): An error occurred trying to start process '/home/pi/0.9.2/.local-chromium/Linux-970485/chrome-linux/chrome' with working directory '/home/pi/0.9.2'. Exec format error
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo , String , String[] , String[] , String , Boolean , UInt32 , UInt32 , UInt32[] , Int32& , Int32& , Int32& , Boolean , Boolean )
   at System.Diagnostics.Process.StartCore(ProcessStartInfo )
   at System.Diagnostics.Process.Start()
   at PuppeteerSharp.States.ChromiumStartingState.StartCoreAsync(LauncherBase p) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\States\ChromiumStartingState.cs:line 68
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Launcher.cs:line 61
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Launcher.cs:line 84
   at MicrosoftRewardsFarmer.PuppeteerUtility.StartNewBrowser_Async(String executablePath, Boolean headless) in C:\Users\Tom60\Nextcloud2\Documents\Projects\dotnet\Microsoft Rewards Farmer\MicrosoftRewards-Farmer\Puppeteer\PuppeteerUtility.cs:line 36
   at MicrosoftRewardsFarmer.TheFarm.Farmer.InitAsync(String browserPath, Int32 farmer_id) in C:\Users\Tom60\Nextcloud2\Documents\Projects\dotnet\Microsoft Rewards Farmer\MicrosoftRewards-Farmer\TheFarm\Farmer.cs:line 95
   at MicrosoftRewardsFarmer.TheFarm.Farmer.FarmPointsAsync(Int32 farmer_id, String browserPath) in C:\Users\Tom60\Nextcloud2\Documents\Projects\dotnet\Microsoft Rewards Farmer\MicrosoftRewards-Farmer\TheFarm\Farmer.cs:line 128
   at MicrosoftRewardsFarmer.Program.<>c__DisplayClass6_0.<<StartFarming>b__0>d.MoveNext() in C:\Users\Tom60\Nextcloud2\Documents\Projects\dotnet\Microsoft Rewards Farmer\MicrosoftRewards-Farmer\Program.cs:line 74
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__50`1.<<ForEachAsync>b__50_0>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
   at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
   at System.Threading.Tasks.Task.Wait()
   at MicrosoftRewardsFarmer.Program.StartFarming() in C:\Users\Tom60\Nextcloud2\Documents\Projects\dotnet\Microsoft Rewards Farmer\MicrosoftRewards-Farmer\Program.cs:line 72
   at MicrosoftRewardsFarmer.Program.Main(String[] args) in C:\Users\Tom60\Nextcloud2\Documents\Projects\dotnet\Microsoft Rewards Farmer\MicrosoftRewards-Farmer\Program.cs:line 35
 ---> (Inner Exception #1) System.ComponentModel.Win32Exception (8): An error occurred trying to start process '/home/pi/0.9.2/.local-chromium/Linux-970485/chrome-linux/chrome' with working directory '/home/pi/0.9.2'. Exec format error
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo , String , String[] , String[] , String , Boolean , UInt32 , UInt32 , UInt32[] , Int32& , Int32& , Int32& , Boolean , Boolean )
   at System.Diagnostics.Process.StartCore(ProcessStartInfo )
   at System.Diagnostics.Process.Start()
   at PuppeteerSharp.States.ChromiumStartingState.StartCoreAsync(LauncherBase p) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\States\ChromiumStartingState.cs:line 68
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Launcher.cs:line 61
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Launcher.cs:line 84
   at MicrosoftRewardsFarmer.PuppeteerUtility.StartNewBrowser_Async(String executablePath, Boolean headless) in C:\Users\Tom60\Nextcloud2\Documents\Projects\dotnet\Microsoft Rewards Farmer\MicrosoftRewards-Farmer\Puppeteer\PuppeteerUtility.cs:line 36
   at MicrosoftRewardsFarmer.TheFarm.Farmer.InitAsync(String browserPath, Int32 farmer_id) in C:\Users\Tom60\Nextcloud2\Documents\Projects\dotnet\Microsoft Rewards Farmer\MicrosoftRewards-Farmer\TheFarm\Farmer.cs:line 95
   at MicrosoftRewardsFarmer.TheFarm.Farmer.FarmPointsAsync(Int32 farmer_id, String browserPath) in C:\Users\Tom60\Nextcloud2\Documents\Projects\dotnet\Microsoft Rewards Farmer\MicrosoftRewards-Farmer\TheFarm\Farmer.cs:line 128
   at MicrosoftRewardsFarmer.Program.<>c__DisplayClass6_0.<<StartFarming>b__0>d.MoveNext() in C:\Users\Tom60\Nextcloud2\Documents\Projects\dotnet\Microsoft Rewards Farmer\MicrosoftRewards-Farmer\Program.cs:line 74
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__50`1.<<ForEachAsync>b__50_0>d.MoveNext()<---

Aborted
pi@bigdata:~/0.9.2 $
```

**Expected behavior**
It working?

**Additional context**

OS: Raspbian GNU/Linux 11 (bullseye) armv7l
Host: Raspberry Pi 3 Model B Plus Rev 1.3
Kernel: 6.1.19-v7+ 

using the browser it automatically downloads at 1st boot. tried all the types of browsers.

Add the latest log file inside the Logs folder inside the app folder. flemme

**Comment by Skeppr** [comment]
Oooohh i think ik why it does that. The browser is arm64 and not arm32 maybe. How do i download a compatible one?

**Comment by Tom60chat** [comment]
Any chrome like browser should do the job.

Anyway, dup of #36.
