### ISSUE TITLE
ummm...

### ISSUE THREAD

**Issue by Dmod134** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#166]
ummm i dont know what this means but can someone explain?
Unhandled exception. Unhandled exception. System.IO.IOException: The process cannot access the file 'C:\Users\(REANACTED ON PUROPSE BY ME)\OneDrive\Desktop\win-x86\Logs\(REANACTED ON PUROPSE BY ME).txt' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String , FileMode , FileAccess , FileShare , FileOptions )
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )
   at System.IO.Strategies.AsyncWindowsFileStreamStrategy..ctor(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )](0/6) - 0 points: Initialization...
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )](0/6) - 0 points: Initialization...
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream , String , FileMode , FileAccess , FileShare , Int32 , FileOptions , Int64 )
   at System.IO.FileStream..ctor(String , FileMode , FileAccess , FileShare , Int32 , FileOptions , Int64 )
   at System.IO.FileStream..ctor(String , FileMode , FileAccess , FileShare , Int32 , FileOptions )
   at System.IO.File.AsyncStreamWriter(String , Encoding , Boolean )
   at System.IO.File.AppendAllTextAsync(String , String , Encoding , CancellationToken )
   at System.IO.File.AppendAllTextAsync(String , String , CancellationToken )
   at MicrosoftRewardsFarmer.Log.Types.FileLogger.Write(String content) in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer.Log/Types/FileLogger.cs:line 38
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object )
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
System.IO.IOException: The process cannot access the file 'C:\Users\ehokt\OneDrive\Desktop\win-x86\Logs\2023-04-28 (REANACTED ON PUROPSE BY ME).txt' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String , FileMode , FileAccess , FileShare , FileOptions )
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )
   at System.IO.Strategies.AsyncWindowsFileStreamStrategy..ctor(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream , String , FileMode , FileAccess , FileShare , Int32 , FileOptions , Int64 )
   at System.IO.FileStream..ctor(String , FileMode , FileAccess , FileShare , Int32 , FileOptions , Int64 )
   at System.IO.FileStream..ctor(String , FileMode , FileAccess , FileShare , Int32 , FileOptions )
   at System.IO.File.AsyncStreamWriter(String , Encoding , Boolean )
   at System.IO.File.AppendAllTextAsync(String , String , Encoding , CancellationToken )
   at System.IO.File.AppendAllTextAsync(String , String , CancellationToken )
   at MicrosoftRewardsFarmer.Log.Types.FileLogger.Write(String content) in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer.Log/Types/FileLogger.cs:line 38
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object )
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

**Comment by DarkEnergy666** [comment]
This is a known issue. Please see my fix on Issue# 110 (one of the last in the long list) or use parameter **--farms-limit 1** (not tested but might fix the problem too).

If you can, please amend the titel of this issue, e.g. 'Bug: being used by another process'

**Comment by Tom60chat** [comment]
Duplicate #119
