### ISSUE TITLE
Crashing on Linux

### ISSUE THREAD

**Issue by Wjouter** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#36]
I've tried to run the latest version (v0.9.1-beta1) on Linux on 2 different machines, a X64 and a arm64 computer. And on both with just running the program with default settings I get this error shown below. It seems to reference library's with their windows paths and can thus not find them. Hope this can help!

```
pi@raspberrypi4Wjouter:~/msfarmer $ ./Microsoft-Rewards-Farmer
Unhandled exception. System.AggregateException: One or more errors occurred. (Failed to launch browser! ) (Failed to launch browser! )                            Version 0.9.1.0 (Latest version)
 ---> PuppeteerSharp.ProcessException: Failed to launch browser!
   at PuppeteerSharp.States.ChromiumStartingState.StartCoreAsync(LauncherBase p) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\States\ChromiumStartingState.cs:line 83
   at PuppeteerSharp.States.ChromiumStartingState.StartCoreAsync(LauncherBase p) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\States\ChromiumStartingState.cs:line 89
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Launcher.cs:line 61
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Launcher.cs:line 84
   at MicrosoftRewardsFarmer.PuppeteerUtility.StartNewBrowser_Async(String executablePath, Boolean headless)
   at MicrosoftRewardsFarmer.TheFarm.Farmer.InitAsync(String browserPath, Int32 farmer_id)
   at MicrosoftRewardsFarmer.TheFarm.Farmer.FarmPointsAsync(Int32 farmer_id, String browserPath)
   at MicrosoftRewardsFarmer.Program.<>c__DisplayClass6_0.<<StartFarming>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__50`1.<<ForEachAsync>b__50_0>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
   at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
   at System.Threading.Tasks.Task.Wait()
   at MicrosoftRewardsFarmer.Program.StartFarming()
   at MicrosoftRewardsFarmer.Program.Main(String[] args)
 ---> (Inner Exception #1) PuppeteerSharp.ProcessException: Failed to launch browser!
   at PuppeteerSharp.States.ChromiumStartingState.StartCoreAsync(LauncherBase p) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\States\ChromiumStartingState.cs:line 83
   at PuppeteerSharp.States.ChromiumStartingState.StartCoreAsync(LauncherBase p) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\States\ChromiumStartingState.cs:line 89
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Launcher.cs:line 61
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Launcher.cs:line 84
   at MicrosoftRewardsFarmer.PuppeteerUtility.StartNewBrowser_Async(String executablePath, Boolean headless)
   at MicrosoftRewardsFarmer.TheFarm.Farmer.InitAsync(String browserPath, Int32 farmer_id)
   at MicrosoftRewardsFarmer.TheFarm.Farmer.FarmPointsAsync(Int32 farmer_id, String browserPath)
   at MicrosoftRewardsFarmer.Program.<>c__DisplayClass6_0.<<StartFarming>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__50`1.<<ForEachAsync>b__50_0>d.MoveNext()<---

Aborted

```

**Comment by Tom60chat** [comment]
Hello, thanks for your feedback.

Can you tries launching the app with the argument: --browser built-in

**Comment by Wjouter** [comment]
Thanks for the reply.

I've tried to launch the program with the argument. And it now works on my x64 machine.

But on my arm64 machine (raspberry pi 4 with 64 bit raspbian) I still get an error:

```
pi@raspberrypi4Wjouter:~/msfarmer $ ./Microsoft-Rewards-Farmer --browser built-in
Unhandled exception. System.AggregateException: One or more errors occurred. (Failed to launch browser! ) (Failed to launch browser! )
 ---> PuppeteerSharp.ProcessException: Failed to launch browser!
   at PuppeteerSharp.States.ChromiumStartingState.StartCoreAsync(LauncherBase p) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\States\ChromiumStartingState.cs:line 83
   at PuppeteerSharp.States.ChromiumStartingState.StartCoreAsync(LauncherBase p) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\States\ChromiumStartingState.cs:line 89
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Launcher.cs:line 61
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Launcher.cs:line 84
   at MicrosoftRewardsFarmer.PuppeteerUtility.StartNewBrowser_Async(String executablePath, Boolean headless)
   at MicrosoftRewardsFarmer.TheFarm.Farmer.InitAsync(String browserPath, Int32 farmer_id)
   at MicrosoftRewardsFarmer.TheFarm.Farmer.FarmPointsAsync(Int32 farmer_id, String browserPath)
   at MicrosoftRewardsFarmer.Program.<>c__DisplayClass6_0.<<StartFarming>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__50`1.<<ForEachAsync>b__50_0>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
   at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
   at System.Threading.Tasks.Task.Wait()
   at MicrosoftRewardsFarmer.Program.StartFarming()
   at MicrosoftRewardsFarmer.Program.Main(String[] args)
 ---> (Inner Exception #1) PuppeteerSharp.ProcessException: Failed to launch browser!
   at PuppeteerSharp.States.ChromiumStartingState.StartCoreAsync(LauncherBase p) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\States\ChromiumStartingState.cs:line 83
   at PuppeteerSharp.States.ChromiumStartingState.StartCoreAsync(LauncherBase p) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\States\ChromiumStartingState.cs:line 89
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Launcher.cs:line 61
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Launcher.cs:line 84
   at MicrosoftRewardsFarmer.PuppeteerUtility.StartNewBrowser_Async(String executablePath, Boolean headless)
   at MicrosoftRewardsFarmer.TheFarm.Farmer.InitAsync(String browserPath, Int32 farmer_id)
   at MicrosoftRewardsFarmer.TheFarm.Farmer.FarmPointsAsync(Int32 farmer_id, String browserPath)
   at MicrosoftRewardsFarmer.Program.<>c__DisplayClass6_0.<<StartFarming>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__50`1.<<ForEachAsync>b__50_0>d.MoveNext()<---

Aborted
```


And after doing some more testing I found that with the arguments: --browser built-in -nh
the x64 machine still crashes with this error:

```

wouter@vmi415648:~/msfarmer$ ./Microsoft-Rewards-Farmer --browser built-in -nh
Microsoft Rewards FarSystem.AggregateException: One or more errors occurred. (Failed to launch browser! [27630:27630:1213/205706.962703:ERROR:ozone_platform_x11.cc(247)] Missing X server or $DISPLAY
) (Failed to launch browser! [27629:27629:1213/205706.961459:ERROR:ozone_platform_x11.cc(247)] Missing X server or $DISPLAY
)
 ---> PuppeteerSharp.ProcessException: Failed to launch browser! [27630:27630:1213/205706.962703:ERROR:ozone_platform_x11.cc(247)] Missing X server or $DISPLAY

   at PuppeteerSharp.States.ChromiumStartingState.StartCoreAsync(LauncherBase p) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\States\ChromiumStartingState.cs:line 83
   at PuppeteerSharp.States.ChromiumStartingState.StartCoreAsync(LauncherBase p) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\States\ChromiumStartingState.cs:line 89
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Launcher.cs:line 61
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Launcher.cs:line 84
   at MicrosoftRewardsFarmer.PuppeteerUtility.StartNewBrowser_Async(String executablePath, Boolean headless)
   at MicrosoftRewardsFarmer.TheFarm.Farmer.InitAsync(String browserPath, Int32 farmer_id)
   at MicrosoftRewardsFarmer.TheFarm.Farmer.FarmPointsAsync(Int32 farmer_id, String browserPath)
   at MicrosoftRewardsFarmer.Program.<>c__DisplayClass6_0.<<StartFarming>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__50`1.<<ForEachAsync>b__50_0>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
   at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
   at System.Threading.Tasks.Task.Wait()
   at MicrosoftRewardsFarmer.Program.StartFarming()
   at MicrosoftRewardsFarmer.Program.Main(String[] args)
 ---> (Inner Exception #1) PuppeteerSharp.ProcessException: Failed to launch browser! [27629:27629:1213/205706.961459:ERROR:ozone_platform_x11.cc(247)] Missing X server or $DISPLAY

   at PuppeteerSharp.States.ChromiumStartingState.StartCoreAsync(LauncherBase p) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\States\ChromiumStartingState.cs:line 83
   at PuppeteerSharp.States.ChromiumStartingState.StartCoreAsync(LauncherBase p) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\States\ChromiumStartingState.cs:line 89
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Launcher.cs:line 61
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Launcher.cs:line 84
   at MicrosoftRewardsFarmer.PuppeteerUtility.StartNewBrowser_Async(String executablePath, Boolean headless)
   at MicrosoftRewardsFarmer.TheFarm.Farmer.InitAsync(String browserPath, Int32 farmer_id)
   at MicrosoftRewardsFarmer.TheFarm.Farmer.FarmPointsAsync(Int32 farmer_id, String browserPath)
   at MicrosoftRewardsFarmer.Program.<>c__DisplayClass6_0.<<StartFarming>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__50`1.<<ForEachAsync>b__50_0>d.MoveNext()<---

Aborted

```

Hope this can help you, and I'l be willing to to some more testing if needed.

**Comment by Tom60chat** [comment]
Hello,

For arm64 well... [This is a known problem for the puppeteer embedded browser](https://github.com/puppeteer/puppeteer/issues/7740), so you should not use the embedded browser for arm64.

Actually, I think it's not a browser problem, but rather an application problem that fails to render.

This application was made and tested on OSs with a built-in desktop interface.

On the puppetteer troubleshooting page, they say that under Unix, you may need some requirement : https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix

**Comment by Wjouter** [comment]
Hello,

I found that when running the program on arm64 works perfectly from the terminal if you specify a browser manually (chromium from my testing). 


But now I've tried to run the program at automated intervals with a cronjob, and now I get a completely different error:

```
[signal: aborted (core dumped)] Unhandled exception. System.ArgumentOutOfRangeException: Length cannot be less than zero. (Parameter 'length')
at System.String.Substring(Int32 startIndex, Int32 length)
at Ez_console.Console.WriteToLine(Object value, Int32 line, Int32 number_of_line, Boolean word_wraping)
at MicrosoftRewardsFarmer.Program.DrawHeader()
at MicrosoftRewardsFarmer.Program.StartFarming()
at MicrosoftRewardsFarmer.Program.Main(String[] args)
```
The program also does not generate a log file when this error occurs. And this occurs on x64 and arm64

I think it may have something to do with the program running as a cronjob and thus not having a terminal to create the gui. 

Hope this could be fixed. Maybe with an option to disable the gui so the program can run completely headless.

**Comment by Wjouter** [comment]
Whoops closed the issue by accident

**Comment by Wjouter** [comment]
Whoops closed the issue by accident

**Comment by Tom60chat** [comment]
Hello,

Well, this is a second issue.

This can be fixed easily.

**Comment by Tom60chat** [comment]
You want an option to diseable the app to write ?

You can do that on linux by doing > /dev/nul

**Comment by Tom60chat** [comment]
Hello, I hope I haven't kept you waiting too long.

Version 0.10 is out, I invite you to test this version.

You can get it at the following address: https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/releases/tag/v0.10.0-beta1

If your problem has been solved, I encourage you to close this issue, you can reopen it if you wish.

**Comment by Tom60chat** [comment]
For cleaning reasons, I will close this issue now, do not hesitate to reopen if the same issue comes back.
