### ISSUE TITLE
[Exception] Farmer - Node is either not visible or not an HTMLElement

### ISSUE THREAD

**Issue by DamsDev1** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#67]
Version: 0.10.0.0 \(Commit: [`30bb3b54ba`](https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/commit/30bb3b54ba19dd69696c75950ddcb81be98decf4))

Logs : [2023-01-24.15.09.26.txt](https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/files/10491173/2023-01-24.15.09.26.txt)

This bug sometimes happens.

**Comment by BigYty** [comment]
[Exception] Farmer - Node is either not visible or not an HTMLElement
+1

**Comment by Tom60chat** [comment]
Hello,

I close this issue because the error occurred on a development version, please reopen it if it still occurs on the release version.

**Comment by Tom60chat** [comment]
This error is still apenning on v0.10.0.1 (check #52)

```
PuppeteerSharp.PuppeteerException: Node is either not visible or not an HTMLElement
   at PuppeteerSharp.ElementHandle.ClickablePointAsync(Nullable`1 offset) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\ElementHandle.cs:line 484
   at PuppeteerSharp.ElementHandle.ClickAsync(ClickOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\ElementHandle.cs:line 188
   at MicrosoftRewardsFarmer.TheFarm.MsRewards.ProceedWKQuizAsync(IPage card_page) in E:\System\Downloads\Microsoft-Rewards-Farmer-Sharp-master\MicrosoftRewards-Farmer\TheFarm\MsRewards.cs:line 323
   at MicrosoftRewardsFarmer.TheFarm.MsRewards.ProceedCardAsync(IPage card_page) in E:\System\Downloads\Microsoft-Rewards-Farmer-Sharp-master\MicrosoftRewards-Farmer\TheFarm\MsRewards.cs:line 280
   at MicrosoftRewardsFarmer.TheFarm.MsRewards.ProceedCardsAsync(IElementHandle[] cardsElement) in E:\System\Downloads\Microsoft-Rewards-Farmer-Sharp-master\MicrosoftRewards-Farmer\TheFarm\MsRewards.cs:line 183
   at MicrosoftRewardsFarmer.TheFarm.Farmer.FarmPointsAsync() in E:\System\Downloads\Microsoft-Rewards-Farmer-Sharp-master\MicrosoftRewards-Farmer\TheFarm\Farmer.cs:line 183
```

**Comment by KendallDoesCoding** [comment]
Any update?
