### ISSUE TITLE
[Exception] `EvaluationFailedException`: Evaluation failed: ReferenceError: `_w` is not defined

### ISSUE THREAD

**Issue by pearlheartgtr** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#70]
[Exception] Farmer - Evaluation failed: ReferenceError: _w is not
defined
    at __puppeteer_evaluation_script__:1:10tion] Farmer - Evaluation failed: ReferenceError: _w is not
defined

**Comment by Tom60chat** [comment]
Hello can you please add the latest log file inside the Logs folder inside the app folder.

**Comment by pearlheartgtr** [comment]
Sorry about that. Here it is:

[Log] 
§cMicrosoft §aRewards §bFarmer §eby §rTom Olivier                                   Version 0.9.3.0 (Checking for new versions...)

[Log] 
§cMicrosoft §aRewards §bFarmer §eby §rTom Olivier                                                 Version 0.9.3.0 (Latest version)

[Log] 
[1](0/6) - 0 points: Restoring session...

[Log] 
[0](0/6) - 0 points: Restoring session...

[Log] 
[2](0/6) - 0 points: Restoring session...

[Log] 
[2](1/6) - 0 points: Obtaining the number of current reward points...

[Log] 
[1](1/6) - 0 points: Obtaining the number of current reward points...

[Log] 
[0](1/6) - 0 points: Obtaining the number of current reward points...

[Log] 
[2](2/6) - 21190 points: Getting cards...

[Log] 
[1](2/6) - 28381 points: Getting cards...

[Log] 
[0](2/6) - 23804 points: Getting cards...

[Log] 
[2](2/6) - 21190 points: Card processing 0 / 7

[Log] 
[1](2/6) - 28381 points: Card processing 0 / 7

[Log] 
[0](2/6) - 23804 points: Card processing 0 / 7

[Exception] 2: Farmer
PuppeteerSharp.EvaluationFailedException: Evaluation failed: ReferenceError: _w is not defined
    at __puppeteer_evaluation_script__:1:10
   at PuppeteerSharp.ExecutionContext.ExecuteEvaluationAsync(String method, Object args) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\ExecutionContext.cs:line 141
   at PuppeteerSharp.ExecutionContext.RemoteObjectTaskToObject[T](Task`1 remote) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\ExecutionContext.cs:line 95
   at PuppeteerSharp.DOMWorld.EvaluateFunctionAsync[T](String script, Object[] args) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\DOMWorld.cs:line 276
   at MicrosoftRewardsFarmer.TheFarm.MsRewards.ProceedQuizCardAsync(IPage card_page, String selector) in C:\Users\Tom60\Nextcloud\Documents\Projects\dotnet\Microsoft Rewards Farmer\MicrosoftRewards-Farmer\TheFarm\MsRewards.cs:line 333
   at MicrosoftRewardsFarmer.TheFarm.MsRewards.ProceedCardAsync(IPage cardPage) in C:\Users\Tom60\Nextcloud\Documents\Projects\dotnet\Microsoft Rewards Farmer\MicrosoftRewards-Farmer\TheFarm\MsRewards.cs:line 283
   at MicrosoftRewardsFarmer.TheFarm.MsRewards.ProceedCardsAsync(IElementHandle[] cardsElement) in C:\Users\Tom60\Nextcloud\Documents\Projects\dotnet\Microsoft Rewards Farmer\MicrosoftRewards-Farmer\TheFarm\MsRewards.cs:line 183
   at MicrosoftRewardsFarmer.TheFarm.Farmer.FarmPointsAsync(Int32 farmer_id, String browserPath) in C:\Users\Tom60\Nextcloud\Documents\Projects\dotnet\Microsoft Rewards Farmer\MicrosoftRewards-Farmer\TheFarm\Farmer.cs:line 169

[Log] 
[2](2/6) - 21190 points: [Exception] Farmer - Evaluation failed: ReferenceError: _w is not defined
    at __puppeteer_evaluation_script__:1:10

[Exception] 1: Farmer
PuppeteerSharp.EvaluationFailedException: Evaluation failed: ReferenceError: _w is not defined
    at __puppeteer_evaluation_script__:1:10
   at PuppeteerSharp.ExecutionContext.ExecuteEvaluationAsync(String method, Object args) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\ExecutionContext.cs:line 141
   at PuppeteerSharp.ExecutionContext.RemoteObjectTaskToObject[T](Task`1 remote) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\ExecutionContext.cs:line 95
   at PuppeteerSharp.DOMWorld.EvaluateFunctionAsync[T](String script, Object[] args) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\DOMWorld.cs:line 276
   at MicrosoftRewardsFarmer.TheFarm.MsRewards.ProceedQuizCardAsync(IPage card_page, String selector) in C:\Users\Tom60\Nextcloud\Documents\Projects\dotnet\Microsoft Rewards Farmer\MicrosoftRewards-Farmer\TheFarm\MsRewards.cs:line 333
   at MicrosoftRewardsFarmer.TheFarm.MsRewards.ProceedCardAsync(IPage cardPage) in C:\Users\Tom60\Nextcloud\Documents\Projects\dotnet\Microsoft Rewards Farmer\MicrosoftRewards-Farmer\TheFarm\MsRewards.cs:line 283
   at MicrosoftRewardsFarmer.TheFarm.MsRewards.ProceedCardsAsync(IElementHandle[] cardsElement) in C:\Users\Tom60\Nextcloud\Documents\Projects\dotnet\Microsoft Rewards Farmer\MicrosoftRewards-Farmer\TheFarm\MsRewards.cs:line 183
   at MicrosoftRewardsFarmer.TheFarm.Farmer.FarmPointsAsync(Int32 farmer_id, String browserPath) in C:\Users\Tom60\Nextcloud\Documents\Projects\dotnet\Microsoft Rewards Farmer\MicrosoftRewards-Farmer\TheFarm\Farmer.cs:line 169

[Log] 
[1](2/6) - 28381 points: [Exception] Farmer - Evaluation failed: ReferenceError: _w is not defined
    at __puppeteer_evaluation_script__:1:10

[Exception] 0: Farmer
PuppeteerSharp.EvaluationFailedException: Evaluation failed: ReferenceError: _w is not defined
    at __puppeteer_evaluation_script__:1:10
   at PuppeteerSharp.ExecutionContext.ExecuteEvaluationAsync(String method, Object args) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\ExecutionContext.cs:line 141
   at PuppeteerSharp.ExecutionContext.RemoteObjectTaskToObject[T](Task`1 remote) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\ExecutionContext.cs:line 95
   at PuppeteerSharp.DOMWorld.EvaluateFunctionAsync[T](String script, Object[] args) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\DOMWorld.cs:line 276
   at MicrosoftRewardsFarmer.TheFarm.MsRewards.ProceedQuizCardAsync(IPage card_page, String selector) in C:\Users\Tom60\Nextcloud\Documents\Projects\dotnet\Microsoft Rewards Farmer\MicrosoftRewards-Farmer\TheFarm\MsRewards.cs:line 333
   at MicrosoftRewardsFarmer.TheFarm.MsRewards.ProceedCardAsync(IPage cardPage) in C:\Users\Tom60\Nextcloud\Documents\Projects\dotnet\Microsoft Rewards Farmer\MicrosoftRewards-Farmer\TheFarm\MsRewards.cs:line 283
   at MicrosoftRewardsFarmer.TheFarm.MsRewards.ProceedCardsAsync(IElementHandle[] cardsElement) in C:\Users\Tom60\Nextcloud\Documents\Projects\dotnet\Microsoft Rewards Farmer\MicrosoftRewards-Farmer\TheFarm\MsRewards.cs:line 183
   at MicrosoftRewardsFarmer.TheFarm.Farmer.FarmPointsAsync(Int32 farmer_id, String browserPath) in C:\Users\Tom60\Nextcloud\Documents\Projects\dotnet\Microsoft Rewards Farmer\MicrosoftRewards-Farmer\TheFarm\Farmer.cs:line 169

[Log] 
[0](2/6) - 23804 points: [Exception] Farmer - Evaluation failed: ReferenceError: _w is not defined
    at __puppeteer_evaluation_script__:1:10

**Comment by Tom60chat** [comment]
Not a dup, but very similar to #55

**Comment by Tom60chat** [comment]
I can even say this is the same error, I will close this one and I invite you to follow #55
I can recommand you to test version 0.9.2 where this issue is not present.
