### ISSUE TITLE
error when launching for the first time

### ISSUE THREAD

**Issue by Skeppr** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#76]
i tried to install this on WSL to see if it works, but when i launch it it gives me this error

`ccapy@heniu-PC:~/msrewards$ ./'Microsoft Rewards Farmer' -nh
Unhandled exception. System.AggregateException: One or more errors occurred. (Failed to launch browser! )king for new versions...)
 ---> PuppeteerSharp.ProcessException: Failed to launch browser!
   at PuppeteerSharp.States.ChromiumStartingState.StartCoreAsync(LauncherBase p) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\States\ChromiumStartingState.cs:line 83
   at PuppeteerSharp.States.ChromiumStartingState.StartCoreAsync(LauncherBase p) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\States\ChromiumStartingState.cs:line 89
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Launcher.cs:line 61
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Launcher.cs:line 84
   at MicrosoftRewardsFarmer.PuppeteerUtility.StartNewBrowser_Async(String executablePath, Boolean headless) in C:\Users\Tom60\Nextcloud\Documents\Projects\dotnet\Microsoft Rewards Farmer\MicrosoftRewards-Farmer\Puppeteer\PuppeteerUtility.cs:line 36
   at MicrosoftRewardsFarmer.TheFarm.Farmer.InitAsync(String browserPath, Int32 farmer_id) in C:\Users\Tom60\Nextcloud\Documents\Projects\dotnet\Microsoft Rewards Farmer\MicrosoftRewards-Farmer\TheFarm\Farmer.cs:line 95
   at MicrosoftRewardsFarmer.TheFarm.Farmer.FarmPointsAsync(Int32 farmer_id, String browserPath) in C:\Users\Tom60\Nextcloud\Documents\Projects\dotnet\Microsoft Rewards Farmer\MicrosoftRewards-Farmer\TheFarm\Farmer.cs:line 128
   at MicrosoftRewardsFarmer.Program.<>c__DisplayClass6_0.<<StartFarming>b__0>d.MoveNext() in C:\Users\Tom60\Nextcloud\Documents\Projects\dotnet\Microsoft Rewards Farmer\MicrosoftRewards-Farmer\Program.cs:line 74
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__50`1.<<ForEachAsync>b__50_0>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
   at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
   at System.Threading.Tasks.Task.Wait()
   at MicrosoftRewardsFarmer.Program.StartFarming() in C:\Users\Tom60\Nextcloud\Documents\Projects\dotnet\Microsoft Rewards Farmer\MicrosoftRewards-Farmer\Program.cs:line 72
   at MicrosoftRewardsFarmer.Program.Main(String[] args) in C:\Users\Tom60\Nextcloud\Documents\Projects\dotnet\Microsoft Rewards Farmer\MicrosoftRewards-Farmer\Program.cs:line 35
Aborted
ccapy@heniu-PC:~/msrewards$`

**Comment by Tom60chat** [comment]
Hello,
First of all, `-nh` mean no headless which will not work on WSL (except maybe on Windows 11 with gWSL).  

And second, the browser failed to launch, which can happen on WSL if it starts the wrong one.
Use `-b built-in`, it will solve the problem.

**Comment by Skeppr** [comment]
nope, still nothing

```
ccapy@heniu-PC:~/msrewards$ ./'Microsoft Rewards Farmer' -b built-in
Unhandled exception. System.AggregateException: One or more errors occurred. (Failed to launch browser! /home/ccapy/msrewards/.local-chromium/Linux-970485/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory
)
 ---> PuppeteerSharp.ProcessException: Failed to launch browser! /home/ccapy/msrewards/.local-chromium/Linux-970485/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory

   at PuppeteerSharp.States.ChromiumStartingState.StartCoreAsync(LauncherBase p) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\States\ChromiumStartingState.cs:line 83
   at PuppeteerSharp.States.ChromiumStartingState.StartCoreAsync(LauncherBase p) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\States\ChromiumStartingState.cs:line 89
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Launcher.cs:line 61
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Launcher.cs:line 84
   at MicrosoftRewardsFarmer.PuppeteerUtility.StartNewBrowser_Async(String executablePath, Boolean headless) in C:\Users\Tom60\Nextcloud\Documents\Projects\dotnet\Microsoft Rewards Farmer\MicrosoftRewards-Farmer\Puppeteer\PuppeteerUtility.cs:line 36
   at MicrosoftRewardsFarmer.TheFarm.Farmer.InitAsync(String browserPath, Int32 farmer_id) in C:\Users\Tom60\Nextcloud\Documents\Projects\dotnet\Microsoft Rewards Farmer\MicrosoftRewards-Farmer\TheFarm\Farmer.cs:line 95
   at MicrosoftRewardsFarmer.TheFarm.Farmer.FarmPointsAsync(Int32 farmer_id, String browserPath) in C:\Users\Tom60\Nextcloud\Documents\Projects\dotnet\Microsoft Rewards Farmer\MicrosoftRewards-Farmer\TheFarm\Farmer.cs:line 128
   at MicrosoftRewardsFarmer.Program.<>c__DisplayClass6_0.<<StartFarming>b__0>d.MoveNext() in C:\Users\Tom60\Nextcloud\Documents\Projects\dotnet\Microsoft Rewards Farmer\MicrosoftRewards-Farmer\Program.cs:line 74
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__50`1.<<ForEachAsync>b__50_0>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
   at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
   at System.Threading.Tasks.Task.Wait()
   at MicrosoftRewardsFarmer.Program.StartFarming() in C:\Users\Tom60\Nextcloud\Documents\Projects\dotnet\Microsoft Rewards Farmer\MicrosoftRewards-Farmer\Program.cs:line 72
   at MicrosoftRewardsFarmer.Program.Main(String[] args) in C:\Users\Tom60\Nextcloud\Documents\Projects\dotnet\Microsoft Rewards Farmer\MicrosoftRewards-Farmer\Program.cs:line 35
Aborted
ccapy@heniu-PC:~/msrewards$
```

**Comment by Tom60chat** [comment]
`error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory` 

That might be why, you missing dependency, you can do :
- Download chrome `sudo apt install chrome`
- Fix it https://gist.github.com/winuxue/cfef08e2f5fe9dfc16a1d67a4ad38a01

**Comment by Tom60chat** [comment]
Hello, @Skeppr 
It's your issue solved?
If yes, you can close it, otherwise I will close it.

**Comment by Tom60chat** [comment]
I will close it, feel free to open it again.
