### ISSUE TITLE
[Exception] `WaitTaskTimeoutException`: waiting for selector 'div[class="points clearfix"]' failed: timeout 30000 ms exceeded

### ISSUE THREAD

**Issue by Gangsh1** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#93]
**Describe the bug**
saw this error message

it lookslike it is taking too long to get cards

stuck in step 2

**Comment by Tom60chat** [comment]
Hello, can you share the last log file in the Logs folder please.

**Comment by Gangsh1** [comment]
[2023-03-01 10.22.18.txt](https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/files/10864521/2023-03-01.10.22.18.txt)

**Comment by Tom60chat** [comment]
```
PuppeteerSharp.WaitTaskTimeoutException: waiting for selector 'div[class="points clearfix"]' failed: timeout 30000 ms exceeded
   at PuppeteerSharp.DOMWorld.WaitForSelectorInPageAsync(String queryOne, String selector, WaitForSelectorOptions options, PageBinding[] bindings) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\DOMWorld.cs:line 447
   at PuppeteerSharp.CustomQueriesManager.<>c__DisplayClass9_0.<<MakeQueryHandler>b__1>d.MoveNext() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\CustomQueriesManager.cs:line 126
--- End of stack trace from previous location ---
   at PuppeteerSharp.DOMWorld.WaitForSelectorAsync(String selector, WaitForSelectorOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\DOMWorld.cs:line 578
   at PuppeteerSharp.Frame.WaitForSelectorAsync(String selector, WaitForSelectorOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Frame.cs:line 124
   at MicrosoftRewardsFarmer.TheFarm.MsRewards.GetCardsAsync() in C:\Users\Tom60\Nextcloud\Documents\Projects\dotnet\Microsoft Rewards Farmer\MicrosoftRewards-Farmer\TheFarm\MsRewards.cs:line 150
   at MicrosoftRewardsFarmer.TheFarm.Farmer.FarmPointsAsync(Int32 farmer_id, String browserPath) in C:\Users\Tom60\Nextcloud\Documents\Projects\dotnet\Microsoft Rewards Farmer\MicrosoftRewards-Farmer\TheFarm\Farmer.cs:line 166
```

An investigation is necessary.
I'll try to see if I can reproduce the problem.

**Comment by Gangsh1** [comment]
Thank you

**Comment by Tom60chat** [comment]
Hello.

Version 0.10 is out, I invite you to test this version.

You can get it at the following address: https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/releases/tag/v0.10.0-beta1

If your problem has been solved, I encourage you to close this issue, you can reopen it if you wish.

**Comment by Tom60chat** [comment]
So I didn't notice but a duplicate have appear so this issue will be continued on here #108
